<BaseScreenView>:
    FitImage:
        id: background
        source: "assets/images/DarkBG.png"
        pos_hint: {'center_x': 0.5,'center_y': 0.5}


<LoadingView>:
    overlay_color: [0, 0, 0, 0.5]
    background_color: [0, 0, 0, 0]
    background: ""

    MDSpinner:
        active: root.active
        size_hint: None, None
        size: dp(46), dp(46)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        color: [1, 1, 1, 1]
